"""add_dc_contacts_address_notes_optional_system

Revision ID: 308349655cb9
Revises: cbf1c4948923
Create Date: 2026-05-15 20:29:57.518447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308349655cb9'
down_revision: Union[str, Sequence[str], None] = 'cbf1c4948923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datacenter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datacenters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('system_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('patch_panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_rack_name_per_dc', ['datacenter_id', 'name'])

    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rack_name_per_dc', type_='unique')
        batch_op.drop_column('notes')

    with op.batch_alter_table('patch_panels', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('system_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('datacenters', schema=None) as batch_op:
        batch_op.drop_column('address')

    op.drop_table('dc_contacts')
    # ### end Alembic commands ###
