"""device_types_lag_fiber_mode_parent_device

Revision ID: 3e19e0cddf47
Revises: 308349655cb9
Create Date: 2026-05-15 23:15:14.742133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e19e0cddf47'
down_revision: Union[str, Sequence[str], None] = '308349655cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('rack_u', sa.Integer(), nullable=True),
    sa.Column('slot_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'model', name='uq_device_type_mfg_model')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lag_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('lag_member_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fiber_mode', sa.String(length=16), nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_device_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slot_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_device_parent', 'devices', ['parent_device_id'], ['id'])
        batch_op.create_foreign_key('fk_device_type_id', 'device_types', ['device_type_id'], ['id'])

    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('switch_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_switch_type_id', 'device_types', ['switch_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('switch_type_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('slot_number')
        batch_op.drop_column('parent_device_id')
        batch_op.drop_column('device_type_id')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_column('fiber_mode')
        batch_op.drop_column('lag_member_index')
        batch_op.drop_column('lag_id')

    op.drop_table('device_types')
    # ### end Alembic commands ###
