"""initial_schema

Revision ID: cbf1c4948923
Revises: 
Create Date: 2026-05-15 19:59:18.443554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf1c4948923'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('datacenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('has_grid_system', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('system_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datacenter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grid_position', sa.String(length=16), nullable=True),
    sa.Column('total_ru', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('datacenter_id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('starting_ru', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patch_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('starting_ru', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('switch_role', sa.String(length=8), nullable=False),
    sa.Column('starting_ru', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=1), nullable=False),
    sa.Column('fabric', sa.String(length=1), nullable=True),
    sa.Column('port_description', sa.String(length=256), nullable=True),
    sa.Column('cable_type', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('system_name_raw', sa.String(length=128), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_name_raw', sa.String(length=128), nullable=True),
    sa.Column('device_serial', sa.String(length=64), nullable=True),
    sa.Column('device_rack_id', sa.Integer(), nullable=True),
    sa.Column('device_rack_name_raw', sa.String(length=128), nullable=True),
    sa.Column('device_grid', sa.String(length=16), nullable=True),
    sa.Column('device_rack_u', sa.Integer(), nullable=True),
    sa.Column('device_slot', sa.String(length=32), nullable=True),
    sa.Column('device_port', sa.String(length=32), nullable=True),
    sa.Column('device_patch_rack_id', sa.Integer(), nullable=True),
    sa.Column('device_patch_rack_name_raw', sa.String(length=128), nullable=True),
    sa.Column('device_patch_ru', sa.Integer(), nullable=True),
    sa.Column('device_patch_side', sa.String(length=4), nullable=True),
    sa.Column('device_patch_module', sa.String(length=16), nullable=True),
    sa.Column('device_patch_port', sa.String(length=16), nullable=True),
    sa.Column('switch_patch_rack_id', sa.Integer(), nullable=True),
    sa.Column('switch_patch_rack_name_raw', sa.String(length=128), nullable=True),
    sa.Column('switch_patch_ru', sa.Integer(), nullable=True),
    sa.Column('switch_patch_side', sa.String(length=4), nullable=True),
    sa.Column('switch_patch_module', sa.String(length=16), nullable=True),
    sa.Column('switch_patch_port', sa.String(length=16), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('switch_name_raw', sa.String(length=128), nullable=True),
    sa.Column('switch_serial', sa.String(length=64), nullable=True),
    sa.Column('switch_rack_id', sa.Integer(), nullable=True),
    sa.Column('switch_rack_name_raw', sa.String(length=128), nullable=True),
    sa.Column('switch_grid', sa.String(length=16), nullable=True),
    sa.Column('switch_rack_u', sa.Integer(), nullable=True),
    sa.Column('switch_slot', sa.String(length=32), nullable=True),
    sa.Column('switch_port', sa.String(length=32), nullable=True),
    sa.Column('vlan_vsan', sa.String(length=256), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('install_status', sa.String(length=32), nullable=False),
    sa.Column('install_notes', sa.Text(), nullable=True),
    sa.Column('seg1_length', sa.String(length=32), nullable=True),
    sa.Column('seg2_length', sa.String(length=32), nullable=True),
    sa.Column('seg3_length', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device_patch_rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['device_rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ),
    sa.ForeignKeyConstraint(['switch_patch_rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['switch_rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index('ix_conn_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_conn_device_port_lookup', ['device_id', 'device_slot', 'device_port'], unique=False)
        batch_op.create_index('ix_conn_switch_port_lookup', ['switch_id', 'switch_slot', 'switch_port'], unique=False)
        batch_op.create_index('ix_conn_work_order', ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index('ix_conn_work_order')
        batch_op.drop_index('ix_conn_switch_port_lookup')
        batch_op.drop_index('ix_conn_device_port_lookup')
        batch_op.drop_index('ix_conn_deleted_at')

    op.drop_table('connections')
    op.drop_table('switches')
    op.drop_table('patch_panels')
    op.drop_table('devices')
    op.drop_table('work_orders')
    op.drop_table('racks')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('systems')
    op.drop_table('datacenters')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
